### PR TITLE
fix error: ws.upgradeReq -> ws.handshake

### PR DESCRIPTION
**Pull request by AlexeyKhristov**

### CODE REVIEW

**Comment by anilanar** [comment]
@AlexeyKhristov What is `ws.handshake`? According to `ws` docs/code, it is still `ws.upgradeReq` even with its latest version: https://github.com/websockets/ws/blob/master/lib/WebSocket.js

And this won't pass tests.

**Comment by AlexeyKhristov** [comment]
@anilanar I tested it with socket.io, not with ws. Compatibility with socket.io is full, except `connection. upgradeReq` changed to `connection. handshake` 

What you think about imlementation support 2 libraries: ws and socket.io?

**Comment by anilanar** [comment]
In that case, let me test it with `socket.io` today. If everything is good, then I will need to create a separate repository because dependencies are different.

**Comment by anilanar** [comment]
@AlexeyKhristov I couldn't make integration tests pass with `socket.io` and `socket.io-client`. There's no support of `socket.io-client` library to inject cookies into handshake requests, I tried patching `XMLHttpRequest` as suggested [here](https://github.com/Automattic/socket.io-client/issues/344#issuecomment-99151852). I don't want to maintain a project without integration tests. If you can make them work, I can support `socket.io`. Otherwise I guess you can use your own fork for your   needs.

Edit: Ideally we could use `PhantomJS` to simulate browser behavior, but it is too much effort for me right now.

**Pull request closed without merging**
